# Generated by Django 3.1.2 on 2020-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201003_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
