# Generated by Django 3.1.2 on 2020-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201012_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
