# Generated by Django 3.1.2 on 2020-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201109_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_tax',
            field=models.IntegerField(default=15),
        ),
    ]
