# Generated by Django 3.1.2 on 2020-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_vat_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('NAI', 'Nairobi'), ('KIS', 'Kisumu'), ('NAK', 'Nakuru'), ('ELD', 'Eldoret'), ('NAV', 'Naivasha'), ('MOM', 'Mombasa')], max_length=200, null=True),
        ),
    ]
