# Generated by Django 3.1.2 on 2020-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201124_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bought',
            field=models.IntegerField(default=False),
        ),
    ]
