# Generated by Django 3.1.2 on 2020-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
